# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHome():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_home(self):
    # Test name: Home
    # Step # | name | target | value | comment
    # 1 | open | https://demo.irplus.in.th/Listed/susco/home.asp |  | 
    self.driver.get("https://demo.irplus.in.th/Listed/susco/home.asp")
    time.sleep(2)
    # 2 | setWindowSize | 1936x1056 |  | 
    self.driver.set_window_size(1936, 1056)
    time.sleep(2)
    # 3 | click | linkText=EN |  | 
    self.driver.find_element(By.LINK_TEXT, "EN").click()
    time.sleep(2)
    # 4 | click | id=slideout-bt |  | 
    self.driver.find_element(By.ID, "slideout-bt").click()
    # 5 | click | linkText=ยอมรับ |  | 
    self.driver.find_element(By.LINK_TEXT, "ยอมรับ").click()
    # 6 | click | css=p:nth-child(3) .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) .read-more").click()
    time.sleep(2)
    # 7 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 8 | click | css=.mb-4:nth-child(5) .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(5) .read-more").click()
    time.sleep(2)
    # 9 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 10 | click | css=.mb-4:nth-child(6) .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(6) .read-more").click()
    time.sleep(2)
    # 11 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 12 | click | css=.mb-4:nth-child(7) .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(7) .read-more").click()
    time.sleep(2)
    # 13 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 14 | click | css=.col-lg-6:nth-child(1) .d-inline-flex > .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-6:nth-child(1) .d-inline-flex > .read-more").click()
    time.sleep(2)
    # 15 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 16 | click | css=.col-lg-6:nth-child(2) > .text-right .d-inline-flex > .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-6:nth-child(2) > .text-right .d-inline-flex > .read-more").click()
    time.sleep(2)
    # 17 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 18 | click | css=.btn-ir2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-ir2").click()
    time.sleep(2)
    # 19 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 20 | click | css=.btn-ir3 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn-ir3").click()
    time.sleep(2)
    # 21 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 22 | click | css=.more-FH .d-inline-flex > .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".more-FH .d-inline-flex > .read-more").click()
    time.sleep(2)
    # 23 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 24 | click | linkText=ดูทั้งหมด |  | 
    self.vars["window_handles"] = self.driver.window_handles
    time.sleep(2)
    # 25 | storeWindowHandle | root |  | 
    self.driver.find_element(By.LINK_TEXT, "ดูทั้งหมด").click()
    time.sleep(2)
    # 26 | selectWindow | handle=${win9595} |  | 
    self.vars["win9595"] = self.wait_for_window(2000)
    time.sleep(2)
    # 27 | close |  |  | 
    self.vars["root"] = self.driver.current_window_handle
    time.sleep(2)
    # 28 | selectWindow | handle=${root} |  | 
    self.driver.switch_to.window(self.vars["win9595"])
    time.sleep(2)
    # 29 | click | linkText=อีเมล |  | 
    self.driver.close()
    time.sleep(2)
    # 30 | selectWindow | handle=${win269} |  | 
    self.driver.switch_to.window(self.vars["root"])
    time.sleep(2)
    # 31 | close |  |  | 
    self.vars["window_handles"] = self.driver.window_handles
    time.sleep(2)
    # 32 | selectWindow | handle=${root} |  | 
    self.driver.find_element(By.LINK_TEXT, "อีเมล").click()
    time.sleep(2)
    # 33 | click | css=.bt-contact > .btn |  | 
    self.vars["win269"] = self.wait_for_window(2000)
    time.sleep(2)
    # 34 | selectWindow | handle=${win347} |  | 
    self.driver.switch_to.window(self.vars["win269"])
    time.sleep(2)
    # 35 | close |  |  | 
    self.driver.close()
    time.sleep(2)
    # 36 | selectWindow | handle=${root} |  | 
    self.driver.switch_to.window(self.vars["root"])
    time.sleep(2)
    # 37 | click | linkText=TH |  | 
    self.vars["window_handles"] = self.driver.window_handles
    time.sleep(2)
    # 38 | click | css=p:nth-child(3) .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".bt-contact > .btn").click()
    time.sleep(2)
    # 39 | runScript | window.history.go(-1) |  | 
    self.vars["win347"] = self.wait_for_window(2000)
    time.sleep(2)
    # 40 | click | css=.mb-4:nth-child(5) .read-more |  | 
    self.driver.switch_to.window(self.vars["win347"])
    time.sleep(2)
    # 41 | runScript | window.history.go(-1) |  | 
    self.driver.close()
    time.sleep(2)
    # 42 | click | css=.mb-4:nth-child(6) .read-more |  | 
    self.driver.switch_to.window(self.vars["root"])
    time.sleep(2)
    self.driver.get("https://demo.irplus.in.th/Listed/susco/home.asp")
    # 43 | runScript | window.history.go(-1) |  | 
    self.driver.find_element(By.LINK_TEXT, "TH").click()
    time.sleep(2)
    # 44 | click | css=.mb-4:nth-child(7) .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) .read-more").click()
    time.sleep(2)
    # 45 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 46 | click | css=.col-lg-6:nth-child(1) .d-inline-flex > .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(5) .read-more").click()
    time.sleep(2)
    # 47 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 48 | click | css=.col-lg-6:nth-child(2) > .text-right .d-inline-flex > .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(6) .read-more").click()
    time.sleep(2)
    # 49 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 50 | click | linkText=ราคาหลักทรัพย์ย้อนหลัง |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(7) .read-more").click()
    time.sleep(2)
    # 51 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 52 | click | linkText=เครื่องคำนวณการลงทุน |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-6:nth-child(1) .d-inline-flex > .read-more").click()
    time.sleep(2)
    # 53 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 54 | click | css=.more-FH .d-inline-flex > .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-6:nth-child(2) > .text-right .d-inline-flex > .read-more").click()
    time.sleep(2)
    # 55 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 56 | click | linkText=ดูทั้งหมด |  | 
    self.driver.find_element(By.LINK_TEXT, "ราคาหลักทรัพย์ย้อนหลัง").click()
    time.sleep(2)
    # 57 | selectWindow | handle=${win6787} |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 58 | close |  |  | 
    self.driver.find_element(By.LINK_TEXT, "เครื่องคำนวณการลงทุน").click()
    time.sleep(2)
    # 59 | selectWindow | handle=${root} |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 60 | click | linkText=อีเมล |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".more-FH .d-inline-flex > .read-more").click()
    time.sleep(2)
    # 61 | selectWindow | handle=${win6097} |  | 
    self.driver.execute_script("window.history.go(-1)")
    time.sleep(2)
    # 62 | close |  |  | 
    self.vars["window_handles"] = self.driver.window_handles
    time.sleep(2)
    # 63 | selectWindow | handle=${root} |  | 
    self.driver.find_element(By.LINK_TEXT, "ดูทั้งหมด").click()
    time.sleep(2)
    # 64 | click | css=.bt-contact > .btn |  | 
    self.vars["win6787"] = self.wait_for_window(2000)
    time.sleep(2)
    # 65 | selectWindow | handle=${win9405} |  | 
    self.driver.switch_to.window(self.vars["win6787"])
    time.sleep(2)
    # 66 | close |  |  | 
    self.driver.close()
    # 67 | selectWindow | handle=${root} |  | 
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.LINK_TEXT, "อีเมล").click()
    self.vars["win6097"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win6097"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".bt-contact > .btn").click()
    self.vars["win9405"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win9405"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
  
